package com.zl.mvpdemo.model.bean.dao.gankDataDb;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.zl.mvpdemo.model.bean.dao.DaoSession;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GANK_DATA_DB".
*/
public class GankDataDBDao extends AbstractDao<GankDataDB, Long> {

    public static final String TABLENAME = "GANK_DATA_DB";

    /**
     * Properties of entity GankDataDB.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Desc = new Property(1, String.class, "desc", false, "desc");
        public final static Property PublishedAt = new Property(2, java.util.Date.class, "publishedAt", false, "publishedAt");
        public final static Property Type = new Property(3, String.class, "type", false, "type");
        public final static Property Url = new Property(4, String.class, "url", false, "url");
        public final static Property Who = new Property(5, String.class, "who", false, "who");
        public final static Property Image_id = new Property(6, int.class, "image_id", false, "image_id");
    }


    public GankDataDBDao(DaoConfig config) {
        super(config);
    }
    
    public GankDataDBDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GANK_DATA_DB\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"desc\" TEXT," + // 1: desc
                "\"publishedAt\" INTEGER," + // 2: publishedAt
                "\"type\" TEXT," + // 3: type
                "\"url\" TEXT UNIQUE ," + // 4: url
                "\"who\" TEXT," + // 5: who
                "\"image_id\" INTEGER NOT NULL );"); // 6: image_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GANK_DATA_DB\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, GankDataDB entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String desc = entity.getDesc();
        if (desc != null) {
            stmt.bindString(2, desc);
        }
 
        java.util.Date publishedAt = entity.getPublishedAt();
        if (publishedAt != null) {
            stmt.bindLong(3, publishedAt.getTime());
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(4, type);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(5, url);
        }
 
        String who = entity.getWho();
        if (who != null) {
            stmt.bindString(6, who);
        }
        stmt.bindLong(7, entity.getImage_id());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, GankDataDB entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String desc = entity.getDesc();
        if (desc != null) {
            stmt.bindString(2, desc);
        }
 
        java.util.Date publishedAt = entity.getPublishedAt();
        if (publishedAt != null) {
            stmt.bindLong(3, publishedAt.getTime());
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(4, type);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(5, url);
        }
 
        String who = entity.getWho();
        if (who != null) {
            stmt.bindString(6, who);
        }
        stmt.bindLong(7, entity.getImage_id());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public GankDataDB readEntity(Cursor cursor, int offset) {
        GankDataDB entity = new GankDataDB( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // desc
            cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)), // publishedAt
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // type
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // url
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // who
            cursor.getInt(offset + 6) // image_id
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, GankDataDB entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDesc(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPublishedAt(cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)));
        entity.setType(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setUrl(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setWho(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setImage_id(cursor.getInt(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(GankDataDB entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(GankDataDB entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(GankDataDB entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
